import "../styles/globals.css";

export const metadata = {
  title: "SAITAN",
  description: "Generated by R.S",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
