import "../styles/globals.css";
import { RootProviders } from "./RootProviders";

export const metadata = {
  title: "SAITAN",
  description: "Generated by R.S",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <RootProviders>{children}</RootProviders>
      </body>
    </html>
  );
}
