"use client";

import Header from "@/components/layouts/Header";

export const metadata = {
  title: "SAITAN-GAME",
  description: "Generated by R.S",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
